name: Build Android VkCube CMake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Ninja
      run: sudo apt-get update && sudo apt-get install -y ninja-build

    - name: Build VkCube APK via Official Script
      run: |
        python3 scripts/android.py --config Release --app-abi 'arm64-v8a' --app-stl c++_shared --apk
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}
        ANDROID_NDK_HOME: ${{ env.ANDROID_HOME }}/ndk-bundle

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vkcube-apk
        path: build-android/bin/*.apk
